package unifi

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi"
)

var (
	_ resource.Resource                = &wireguardPeerResource{}
	_ resource.ResourceWithImportState = &wireguardPeerResource{}
)

func NewWireGuardPeerResource() resource.Resource {
	return &wireguardPeerResource{}
}

type wireguardPeerResource struct {
	client *Client
}

type wireguardPeerResourceModel struct {
	ID                types.String `tfsdk:"id"`
	Site              types.String `tfsdk:"site"`
	Name              types.String `tfsdk:"name"`
	WireGuardServerID types.String `tfsdk:"wireguard_server_id"`
	IP                types.String `tfsdk:"ip"`
	PublicKey         types.String `tfsdk:"public_key"`
	Enabled           types.Bool   `tfsdk:"enabled"`
}

func (r *wireguardPeerResource) Metadata(
	ctx context.Context,
	req resource.MetadataRequest,
	resp *resource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_wireguard_peer"
}

func (r *wireguardPeerResource) Schema(
	ctx context.Context,
	req resource.SchemaRequest,
	resp *resource.SchemaResponse,
) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "`unifi_wireguard_peer` manages WireGuard VPN peers on a UniFi WireGuard server. " +
			"The controller auto-generates the keypair and assigns an IP address when a peer is created.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The ID of the WireGuard peer.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"site": schema.StringAttribute{
				MarkdownDescription: "The name of the site to associate the WireGuard peer with.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the WireGuard peer.",
				Required:            true,
			},
			"wireguard_server_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the WireGuard VPN server this peer belongs to.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"ip": schema.StringAttribute{
				MarkdownDescription: "The tunnel IP address assigned to this peer by the controller.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"public_key": schema.StringAttribute{
				MarkdownDescription: "The WireGuard public key generated by the controller for this peer.",
				Computed:            true,
				Sensitive:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Specifies whether the WireGuard peer is enabled.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
			},
		},
	}
}

func (r *wireguardPeerResource) Configure(
	ctx context.Context,
	req resource.ConfigureRequest,
	resp *resource.ConfigureResponse,
) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf(
				"Expected *Client, got: %T. Please report this issue to the provider developers.",
				req.ProviderData,
			),
		)
		return
	}

	r.client = client
}

func (r *wireguardPeerResource) Create(
	ctx context.Context,
	req resource.CreateRequest,
	resp *resource.CreateResponse,
) {
	var data wireguardPeerResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	site := data.Site.ValueString()
	if site == "" {
		site = r.client.Site
	}

	peer := &unifi.WireGuardPeer{
		Name:              data.Name.ValueString(),
		WireGuardServerID: data.WireGuardServerID.ValueString(),
		Enabled:           data.Enabled.ValueBool(),
	}

	created, err := r.client.CreateWireGuardPeer(ctx, site, peer)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating WireGuard Peer",
			err.Error(),
		)
		return
	}

	r.peerToModel(created, &data, site)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *wireguardPeerResource) Read(
	ctx context.Context,
	req resource.ReadRequest,
	resp *resource.ReadResponse,
) {
	var data wireguardPeerResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	site := data.Site.ValueString()
	if site == "" {
		site = r.client.Site
	}

	peer, err := r.client.GetWireGuardPeer(ctx, site, data.ID.ValueString())
	if err != nil {
		if _, ok := err.(*unifi.NotFoundError); ok {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error Reading WireGuard Peer",
			"Could not read WireGuard peer with ID "+data.ID.ValueString()+": "+err.Error(),
		)
		return
	}

	r.peerToModel(peer, &data, site)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *wireguardPeerResource) Update(
	ctx context.Context,
	req resource.UpdateRequest,
	resp *resource.UpdateResponse,
) {
	var data wireguardPeerResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	site := data.Site.ValueString()
	if site == "" {
		site = r.client.Site
	}

	peer := &unifi.WireGuardPeer{
		ID:                data.ID.ValueString(),
		Name:              data.Name.ValueString(),
		WireGuardServerID: data.WireGuardServerID.ValueString(),
		Enabled:           data.Enabled.ValueBool(),
	}

	updated, err := r.client.UpdateWireGuardPeer(ctx, site, peer)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Updating WireGuard Peer",
			err.Error(),
		)
		return
	}

	r.peerToModel(updated, &data, site)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *wireguardPeerResource) Delete(
	ctx context.Context,
	req resource.DeleteRequest,
	resp *resource.DeleteResponse,
) {
	var data wireguardPeerResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	site := data.Site.ValueString()
	if site == "" {
		site = r.client.Site
	}

	err := r.client.DeleteWireGuardPeer(ctx, site, data.ID.ValueString())
	if err != nil {
		if _, ok := err.(*unifi.NotFoundError); ok {
			return
		}
		resp.Diagnostics.AddError(
			"Error Deleting WireGuard Peer",
			err.Error(),
		)
		return
	}
}

func (r *wireguardPeerResource) ImportState(
	ctx context.Context,
	req resource.ImportStateRequest,
	resp *resource.ImportStateResponse,
) {
	idParts := strings.Split(req.ID, ":")

	if len(idParts) == 2 {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("site"), idParts[0])...)
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), idParts[1])...)
		return
	}

	if len(idParts) == 1 {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
		return
	}

	resp.Diagnostics.AddError(
		"Invalid Import ID",
		"Import ID must be in format 'site:id' or 'id'",
	)
}

func (r *wireguardPeerResource) peerToModel(
	peer *unifi.WireGuardPeer,
	model *wireguardPeerResourceModel,
	site string,
) {
	model.ID = types.StringValue(peer.ID)
	model.Site = types.StringValue(site)
	model.Name = types.StringValue(peer.Name)
	model.WireGuardServerID = types.StringValue(peer.WireGuardServerID)
	model.Enabled = types.BoolValue(peer.Enabled)

	if peer.IP != "" {
		model.IP = types.StringValue(peer.IP)
	} else {
		model.IP = types.StringNull()
	}

	if peer.PublicKey != "" {
		model.PublicKey = types.StringValue(peer.PublicKey)
	} else {
		model.PublicKey = types.StringNull()
	}
}
